Added OLA management
synthesio/infra-ovh-ansible-module pull request #107
Opened 2024-12-13 21:41 UTC by Fry-4TF1V

Added support for OLA. Possible to aggregate/deaggregate all interfaces at once.

2025-01-06 14:00 UTC, tortuegenialez requested changes
Thank you for this PR.
We made some changes since your previous PR:
- The OVH class is handling calls and errors
- We try to normalise f-string usage

2025-01-06 14:00 UTC, tortuegenialez commented on plugins/modules/dedicated_server_networkinterfacecontroller.py
> +# porut
I'm not sure about that :D

2025-01-06 14:00 UTC, tortuegenialez commented on plugins/modules/dedicated_server_networkinterfacecontroller.py
>          description: The service_name
Could you change the description?
```suggestion
        description: The service name
```

2025-01-06 14:00 UTC, tortuegenialez commented on plugins/modules/dedicated_server_ola_configure.py
> +try:
This is handled in the OVH class

2025-01-06 14:00 UTC, tortuegenialez commented on plugins/modules/dedicated_server_ola_configure.py
> +    delegate_to: localhost
The module returns the task id, it could be usefull to add a `register` here.

2025-01-06 14:00 UTC, tortuegenialez commented on plugins/modules/dedicated_server_ola_configure.py
> +RETURN = ''' # '''
We are not consistent on this but could you add the data returned?

2025-01-06 14:00 UTC, tortuegenialez commented on plugins/modules/dedicated_server_ola_configure.py
> +    except APIError as api_error:
Exceptions are supposed to be catched by the OVH class, do you need this here?

2025-01-06 14:00 UTC, tortuegenialez commented on plugins/modules/dedicated_server_ola_configure.py
> +        module.exit_json(msg="OLA configuration in progress on {} with aggregate name {} - (dry run mode)"
Please use f-strings for consistency

2025-01-06 14:00 UTC, tortuegenialez commented on plugins/modules/dedicated_server_ola_unconfigure.py
> +#!/usr/bin/python
Same remarks as in the previous module

2025-01-06 14:00 UTC, tortuegenialez commented on plugins/modules/dedicated_server_ola_wait.py
> +try:
This is handled in the OVH class

2025-01-06 14:00 UTC, tortuegenialez commented on plugins/modules/dedicated_server_ola_wait.py
> +        except APIError as api_error:
This is handled in the OVH class too

2025-01-06 14:00 UTC, tortuegenialez commented on plugins/modules/dedicated_server_ola_wait.py
> +            module.exit_json(msg="{}: {}".format(result['status'], message), changed=False)
Use f-string

2025-01-07 21:56 UTC, Fry-4TF1V commented
Hi @tortuegenialez,

I'm not an expert in Git, so tried to do my best to update files as requested. Hope it is good now.

2025-01-09 15:26 UTC, tortuegenialez reviewed
Thanks for the modifications, I'm in doubt with the indentation of 2 lignes

2025-01-09 15:26 UTC, tortuegenialez commented on plugins/modules/dedicated_server_ola_configure.py
> +                       name=aggregate_name, virtualNetworkInterfaces=virtualNetworkInterfaces)
Those 2 lignes seems badly indented, no?

2025-01-15 13:42 UTC, tortuegenialez approved these changes
Thanks!

2026-04-22 12:37 UTC, merged