Jt/add dedicated server intervention
synthesio/infra-ovh-ansible-module pull request #108
Opened 2024-12-20 17:31 UTC by tnosaj

Adds ability to enable or disable the manual intervention done by the OVH team: [reference](https://eu.api.ovh.com/console/?section=%2Fdedicated%2Fserver&branch=v1#put-/dedicated/server/-serviceName-)

Somewhat counter intuitively the variable is already a negative (`noIntervetion` in the server object)  - thus the option was abstracted a bit to be more readable:

```
- name: "Enable proactive intervention on dedicated server {{ service_name }}"
  synthesio.ovh.dedicated_server_intervention:
    service_name: "{{ service_name }}"
    state: enabled
  delegate_to: localhost
```

2025-01-03 08:39 UTC, tortuegenialez requested changes
Thank you for your contribution

2025-01-03 08:39 UTC, tortuegenialez commented on plugins/modules/dedicated_server_intervention.py
> +author: Synthesio SRE Team
You are the author here :)

2025-01-03 08:39 UTC, tortuegenialez commented on plugins/modules/dedicated_server_intervention.py
> +        description: The service_name
No need for snake case: 
```suggestion
        description: The service name
```

2025-01-03 08:39 UTC, tortuegenialez commented on plugins/modules/dedicated_server_intervention.py
> +        required: true
The default is `disabled`, it is not required
```suggestion
        required: false
```

2025-01-03 08:39 UTC, tortuegenialez commented on plugins/modules/dedicated_server_intervention.py
> +        noIntervention_bool = False
We use snake case in the module, could you rather use something like
```suggestion
        no_intervention_bool = False
```

2025-01-03 08:55 UTC, tnosaj commented on plugins/modules/dedicated_server_intervention.py
> +author: Synthesio SRE Team
copy/pasta fail

2025-01-03 08:55 UTC, tnosaj commented on plugins/modules/dedicated_server_intervention.py
> +        noIntervention_bool = False
sure - done

2025-01-03 08:55 UTC, tnosaj commented
happy holidays, and thanks for your review

2025-01-09 10:59 UTC, tortuegenialez approved these changes
Thanks

2025-01-28 09:59 UTC, tnosaj commented
Hey folks - Did i miss anything on this PR or is there a different reason why its not merged?

2025-01-30 08:36 UTC, merged