VPS Info Module - Supports: Ok
synthesio/infra-ovh-ansible-module pull request #78
Opened 2024-03-22 14:59 UTC by armorica

Hi,

First code for an Ansible module for retrieving theIinfo of a OVH VPS system.
- Take the Service Name as parameter.
- Report VPS Info

No error handling for the GET (yet).

Based on the dedicated_server_info.py so I kept the author from that one and added mine.

Regards,

Paul Tap (armorica)

2024-04-17 10:03 UTC, tortuegenialez requested changes
Thanks for this module

2024-04-17 10:03 UTC, tortuegenialez commented on plugins/modules/vps_info.py
> +        description: The service_name
No need for the underscore: `The service name`

2024-04-17 10:03 UTC, tortuegenialez commented on plugins/modules/vps_info.py
> +  register: dedicated_info
`vps_info` would be more appropriate

2024-05-13 15:22 UTC, Skunnyk approved these changes

2024-05-13 15:28 UTC, tortuegenialez approved these changes

2024-05-13 15:28 UTC, merged