New module public_cloud_sshkey
synthesio/infra-ovh-ansible-module pull request #91
Opened 2024-07-23 19:53 UTC by m-sarti

2024-07-26 14:42 UTC, tortuegenialez requested changes
Thank you for this PR
To avoid confusion with ssh key under the `/me` route could you be more explicit on parameter.
For expemple `public_key` could be `public_cloud_ssh_key` ?

2024-07-26 14:42 UTC, tortuegenialez commented on plugins/modules/public_cloud_sshkey.py
> +                             msg="Key {} is already present".format(name))
For consistency in the module can you use fstring too here?
```suggestion
                             msg=f"Key {name} is already present")
```

2024-08-02 08:32 UTC, tortuegenialez approved these changes

2024-08-02 08:36 UTC, carrouet approved these changes

2024-08-02 08:40 UTC, merged