Exposes JBOD mode on server installation
synthesio/infra-ovh-ansible-module pull request #92
Opened 2024-08-12 15:34 UTC by tnosaj

Adds ability to bypass software raid all together by using the `noRaid` flag: [reference](https://eu.api.ovh.com/console/?section=%2Fdedicated%2Fserver&branch=v1#post-/dedicated/server/-serviceName-/install/start)

The alternative is that an `md` device is created and all the disks are passed in. if 0 disks are specified the api just fails. Using `noRaid` is the only way to fully bypass any `md` device creation and install the os on disk 0, and pass the rest as JBOD

2024-08-19 14:08 UTC, tnosaj commented
Thanks @tortuegenialez - i applied your suggestion - makes sense to make it explicit.

2024-08-20 07:05 UTC, tortuegenialez approved these changes

2024-08-20 07:08 UTC, tortuegenialez requested changes

2024-08-20 07:08 UTC, tortuegenialez commented on plugins/modules/dedicated_server_install.py
> +                "noRaid": no_raid }
The linter complains on this line: `E202 whitespace before '}'`
```suggestion
                "noRaid": no_raid}
```

2024-08-20 07:18 UTC, tnosaj commented
Sorry about the lint fail, i will setup flake for future PRs :)

2024-08-20 09:38 UTC, tortuegenialez approved these changes
Thanks

2024-08-20 09:51 UTC, carrouet approved these changes
Note sure if `soft_raid` would have been better than `raid` as option name (to match `soft_raid_devices` naming), but since it is already no consistent at OVH level, let's stay with this.

2024-08-21 09:04 UTC, merged